#ifndef	__WLCMDLABEL_H_
#define	__WLCMDLABEL_H_

#define	WL_CMDLABEL_RST_MIB_HOLD			0
#define	WL_CMDLABEL_RST_MIB_CLR				1

#define	WL_CMDLABEL_PMG_CONT_ACT			0
#define	WL_CMDLABEL_PMG_PS					1
#define	WL_CMDLABEL_WAKEUP_CONT_SLEEP		1
#define	WL_CMDLABEL_WAKEUP_NORMAL			0
#define	WL_CMDLABEL_RX_ALL_DTIM				1
#define	WL_CMDLABEL_OBEY_LSTN_INV			0

#define	WL_CMDLABEL_SCAN_ACTIVE				0
#define	WL_CMDLABEL_SCAN_PASSIVE			1

#define	WL_CMDLABEL_AUTH_OPEN_SYSTEM		0
#define	WL_CMDLABEL_AUTH_SHARED_KEY			1

#define	WL_CMDLABEL_STS_SUCCESSFUL					0
#define	WL_CMDLABEL_STS_UNSPECIFIED					1
#define	WL_CMDLABEL_STS_NOT_SUPPORT_CAPABILITY		10
#define	WL_CMDLABEL_STS_REASS_INABILITY				11
#define	WL_CMDLABEL_STS_OUT_OF_STANDARD				12
#define	WL_CMDLABEL_STS_NOT_SUPPORT_AUTH_ALGORITHM	13
#define	WL_CMDLABEL_STS_OUT_OF_AUTH_SEQ_NUM			14
#define	WL_CMDLABEL_STS_CHALLENGE_FAILURE			15
#define	WL_CMDLABEL_STS_AUTH_TIMEOUT				16
#define	WL_CMDLABEL_STS_ASS_UNABLE_HANDLE			17
#define	WL_CMDLABEL_STS_INVALID_BASICRATESET		18
#define	WL_CMDLABEL_STS_NO_ENTRY					19

#define	WL_CMDLABEL_RSN_RESERVED					0
#define	WL_CMDLABEL_RSN_UNSPECIFIED					1
#define	WL_CMDLABEL_RSN_PREV_AUTH_INVALID			2
#define	WL_CMDLABEL_RSN_DEAUTH_LEAVING				3
#define	WL_CMDLABEL_RSN_INACTIVE					4
#define	WL_CMDLABEL_RSN_UNABLE_HANDLE				5
#define	WL_CMDLABEL_RSN_RX_CLASS2_FROM_NONAUTH_STA	6
#define	WL_CMDLABEL_RSN_RX_CLASS3_FROM_NONASS_STA	7
#define	WL_CMDLABEL_RSN_DISASS_LEAVING				8
#define	WL_CMDLABEL_RSN_ASS_STA_NOTAUTHED			9
#define	WL_CMDLABEL_RSN_NO_ENTRY					19

#define	WL_CMDLABEL_CCA_MODE0				0
#define	WL_CMDLABEL_CCA_MODE1				1
#define	WL_CMDLABEL_CCA_MODE2				2
#define	WL_CMDLABEL_CCA_MODE3				3

#define	WL_CMDLABEL_MP_RESUME_EN			0x8000
#define	WL_CMDLABEL_MP_RESUME_RATE			0x0001
#define	WL_CMDLABEL_MP_RESUME_TXOP			0x0002
#define	WL_CMDLABEL_MP_RESUME_BITMAP		0x0004
#define	WL_CMDLABEL_MP_RESUME_TMPTT			0x0008
#define	WL_CMDLABEL_MP_RESUME_DATA			0x0010
#define	WL_CMDLABEL_MP_TXOP_TIME			0x8000

#define	WL_CMDLABEL_CLRDATA_KEYDATA			0x0001
#define	WL_CMDLABEL_CLRDATA_MP				0x0002
#define	WL_CMDLABEL_CLRDATA_DATA				0x0004

#define	WL_CMDLABEL_ENCH_FCC				0x0FFE
#define	WL_CMDLABEL_ENCH_IC					0x0FFE
#define	WL_CMDLABEL_ENCH_ETSI				0x3FFE
#define	WL_CMDLABEL_ENCH_SPAIN				0x0C00
#define	WL_CMDLABEL_ENCH_FRANCE				0x3C00
#define	WL_CMDLABEL_ENCH_MKK				0x7FFE

#define	WL_CMDLABEL_MODE_TEST				0
#define	WL_CMDLABEL_MODE_PARENT				1
#define	WL_CMDLABEL_MODE_CHILD				2
#define	WL_CMDLABEL_MODE_HOTSPOT			3

#define	WL_CMDLABEL_RATE_AUTO				0
#define	WL_CMDLABEL_RATE_1M					1
#define	WL_CMDLABEL_RATE_2M					2

#define	WL_CMDLABEL_WEP_NO					0
#define	WL_CMDLABEL_WEP_RC4_40				1
#define	WL_CMDLABEL_WEP_RC4_104				2
#define	WL_CMDLABEL_WEP_RC4_128				3

#define	WL_CMDLABEL_INCLUDE_SSID			0
#define	WL_CMDLABEL_NOT_INCLUDE_SSID		1

#define	WL_CMDLABEL_RESPONSE_BC_PRBREQ		0
#define	WL_CMDLABEL_NOT_RESPONSE_BC_PRBREQ	1

#define	WL_CMDLABEL_PREAMBLE_LONG			0
#define	WL_CMDLABEL_PREAMBLE_SHORT			1

#define	WL_CMDLABEL_TXPOWER_0DBM			0
#define	WL_CMDLABEL_TXPOWER_10DBM			1

#define	WL_CMDLABEL_MAIN_ANTENNA_1			0
#define	WL_CMDLABEL_MAIN_ANTENNA_2			1

#define	WL_CMDLABEL_DIVERSITY_OFF			0
#define	WL_CMDLABEL_DIVERSITY_ON			1
#define	WL_CMDLABEL_USE_MAIN_ANTENNA		0
#define	WL_CMDLABEL_USE_SUB_ANTENNA			1

#define	WL_CMDLABEL_BCNIND_OFF				0
#define	WL_CMDLABEL_BCNIND_ON				1

#define	WL_CMDLABEL_NULLKEY_DISABLE			0
#define	WL_CMDLABEL_NULLKEY_ENABLE			1

#define	WL_CMDLABEL_TEST_SIGNAL_OFF			0
#define	WL_CMDLABEL_TEST_SIGNAL_ON			1
#define	WL_CMDLABEL_TEST_SIGNAL_NOMOD		0
#define	WL_CMDLABEL_TEST_SIGNAL_NOMOD_0		0
#define	WL_CMDLABEL_TEST_SIGNAL_NOMOD_1		1
#define	WL_CMDLABEL_TEST_SIGNAL_PN15		2
#define	WL_CMDLABEL_TEST_SIGNAL_01PTN_SCR_ON	3
#define	WL_CMDLABEL_TEST_SIGNAL_01PTN_SCR_OFF	4
#define	WL_CMDLABEL_TEST_SIGNAL_1M			0x0a
#define	WL_CMDLABEL_TEST_SIGNAL_2M			0x14

#define	WL_CMDLABEL_TEST_RX_OFF				0
#define	WL_CMDLABEL_TEST_RX_ON				1

#define	WL_STA_SHUTDOWN						0x00
#define	WL_STA_IDLE							0x10
#define	WL_STA_IDLE_TEST					0x11
#define	WL_STA_IDLE_TEST2					0x12
#define	WL_STA_CLASS1						0x20
#define	WL_STA_CLASS2						0x30
#define	WL_STA_CLASS3						0x40


#define	WL_FATAL_ERR_NOT_ENOUGH_MEMORY			0x0001
#define	WL_FATAL_ERR_NOT_ENOUGH_MEMORY_MANCTRL	0x0002
#define	WL_FATAL_ERR_NOT_ENOUGH_MEMORY_DEFRAG	0x0004
#define	WL_FATAL_ERR_NOT_ENOUGH_MEMORY_RXFRM	0x0008
#define	WL_FATAL_ERR_NOT_ENOUGH_MEMORY_RXMP		0x0010
#define	WL_FATAL_ERR_TXKEY_BUT_NOT_RXMP			0x0020
#define	WL_FATAL_ERR_CONTINUOUS_TX				0x0040

#define	WL_DIAG_ERR_MAC_REG					0x0001
#define	WL_DIAG_ERR_MAC_RAM					0x0002
#define	WL_DIAG_ERR_MAC_DMA					0x0004
#define	WL_DIAG_ERR_BBP_REG					0x0008
#define	WL_DIAG_ERR_EEPROM_ACC				0x0010
#define	WL_DIAG_ERR_EEPROM_CRC				0x0020
#define	WL_DIAG_ERR_ALARM					0x0040
#define	WL_DIAG_ERR_CHECKSUM				0x0080
#define	WL_DIAG_ERR_RF_REG					0x0100
#define	WL_DIAG_ERR_RF_LD					0x0200

#endif	// __WLCMDLABEL_H_

