option('mwrap_ver', type: 'string', value: 'default', description: 'Version of Metrowerks toolchain to use')
option('mwrap_sdk', type: 'string', value: 'default', description: 'Version of Metrowerks libraries to use')
option('sp1p3_conditionals', type: 'boolean', value: false)
option('mwrap_libos', type: 'string', value: 'default', description: 'Version of Metrowerks for libos to use')
option('mwrap_libcard', type: 'string', value: 'default', description: 'Version of Metrowerks for libcard to use')
option('mwrap_arm7', type: 'string', value: 'default', description: 'Version of Metrowerks for the arm7 binary to use')
option('mwrap_libwl_arm7', type: 'string', value: 'default', description: 'Version of Metrowerks for arm7 libwl to use')
option('patch3', type: 'boolean', value: false)
option('irc_support', type: 'boolean', value: false)
