libcard_srcs = files(
    'card_common.c',
    'card_spi.c',
    'card_backup.c',
    'card_rom.c',
    'card_request.c',
    'card_pullOut.c'
)

libcard_arm7_srcs = files(
    'card_common.c',
    'card_spi.c',
    'card_backup.c',
    'card_rom.c',
    'ARM7/card_request.c',
    'ARM7/card_pullOut.c',
)
