#ifndef __MAC_H_
#define __MAC_H_

#define NEW_SDV 1
// #define	NEW_SDV			0

#define MREG_VERSION  (MAC_REG_BASE + OFST_MREG_VERSION)
#define MREG_CMD      (MAC_REG_BASE + OFST_MREG_CMD)
#define MREG_CONFIG   (MAC_REG_BASE + OFST_MREG_CONFIG)
#define MREG_TXCONFIG (MAC_REG_BASE + OFST_MREG_TXCONFIG)
#define MREG_RXCONFIG (MAC_REG_BASE + OFST_MREG_RXCONFIG)
#define MREG_ISR      (MAC_REG_BASE + OFST_MREG_ISR)
#define MREG_IMR      (MAC_REG_BASE + OFST_MREG_IMR)

#define MREG_MAC_ADRS        (MAC_REG_BASE + OFST_MREG_MAC_ADRS)
#define MREG_MAC_ADRS0       (MAC_REG_BASE + OFST_MREG_MAC_ADRS0)
#define MREG_MAC_ADRS1       (MAC_REG_BASE + OFST_MREG_MAC_ADRS1)
#define MREG_MAC_ADRS2       (MAC_REG_BASE + OFST_MREG_MAC_ADRS2)
#define MREG_BSSID           (MAC_REG_BASE + OFST_MREG_BSSID)
#define MREG_BSSID0          (MAC_REG_BASE + OFST_MREG_BSSID0)
#define MREG_BSSID1          (MAC_REG_BASE + OFST_MREG_BSSID1)
#define MREG_BSSID2          (MAC_REG_BASE + OFST_MREG_BSSID2)
#define MREG_KSID            (MAC_REG_BASE + OFST_MREG_KSID)
#define MREG_AID             (MAC_REG_BASE + OFST_MREG_AID)
#define MREG_RETRY_LIMIT     (MAC_REG_BASE + OFST_MREG_RETRY_LIMIT)
#define MREG_BASIC_RATE      (MAC_REG_BASE + OFST_MREG_BASIC_RATE)
#define MREG_TXPREAMBLE_TYPE (MAC_REG_BASE + OFST_MREG_TXPREAMBLE_TYPE)

#define MREG_BUF_SELECT (MAC_REG_BASE + OFST_MREG_BUF_SELECT)
#define MREG_DS_MASK    (MAC_REG_BASE + OFST_MREG_DS_MASK)

#define MREG_SET_POWER       (MAC_REG_BASE + OFST_MREG_SET_POWER)
#define MREG_SET_FORCE_POWER (MAC_REG_BASE + OFST_MREG_SET_FORCE_POWER)
#define MREG_MP_POWER_SEQ    (MAC_REG_BASE + OFST_MREG_MP_POWER_SEQ)

#define MREG_TSF_ENABLE   (MAC_REG_BASE + OFST_MREG_TSF_ENABLE)
#define MREG_TBTT_ENABLE  (MAC_REG_BASE + OFST_MREG_TBTT_ENABLE)
#define MREG_NAV_ENABLE   (MAC_REG_BASE + OFST_MREG_NAV_ENABLE)
#define MREG_TMPTT_ENABLE (MAC_REG_BASE + OFST_MREG_TMPTT_ENABLE)

#define MREG_TSF            (MAC_REG_BASE + OFST_MREG_TSF)
#define MREG_TSF0           (MAC_REG_BASE + OFST_MREG_TSF0)
#define MREG_TSF1           (MAC_REG_BASE + OFST_MREG_TSF1)
#define MREG_TSF2           (MAC_REG_BASE + OFST_MREG_TSF2)
#define MREG_TSF3           (MAC_REG_BASE + OFST_MREG_TSF3)
#define MREG_NEXT_TBTT_TSF  (MAC_REG_BASE + OFST_MREG_NEXT_TBTT_TSF)
#define MREG_NEXT_TBTT_TSF0 (MAC_REG_BASE + OFST_MREG_NEXT_TBTT_TSF0)
#define MREG_NEXT_TBTT_TSF1 (MAC_REG_BASE + OFST_MREG_NEXT_TBTT_TSF1)
#define MREG_NEXT_TBTT_TSF2 (MAC_REG_BASE + OFST_MREG_NEXT_TBTT_TSF2)
#define MREG_NEXT_TBTT_TSF3 (MAC_REG_BASE + OFST_MREG_NEXT_TBTT_TSF3)
#define MREG_RXED_TSF       (MAC_REG_BASE + OFST_MREG_RXED_TSF)
#define MREG_RXED_TSF0      (MAC_REG_BASE + OFST_MREG_RXED_TSF0)
#define MREG_RXED_TSF1      (MAC_REG_BASE + OFST_MREG_RXED_TSF1)
#define MREG_RXED_TSF2      (MAC_REG_BASE + OFST_MREG_RXED_TSF2)
#define MREG_RXED_TSF3      (MAC_REG_BASE + OFST_MREG_RXED_TSF3)

#define MREG_TS_TXOFST (MAC_REG_BASE + OFST_MREG_TS_TXOFST)
#define MREG_TS_RXOFST (MAC_REG_BASE + OFST_MREG_TS_RXOFST)
#define MREG_TIMEOUT   (MAC_REG_BASE + OFST_MREG_RESPONSE_TIMEOUT)
#define MREG_TIME_STS  (MAC_REG_BASE + OFST_MREG_TIME_STS)
#define MREG_NAV       (MAC_REG_BASE + OFST_MREG_NAV)

#define MREG_BCN_ADRS      (MAC_REG_BASE + OFST_MREG_BCN_ADRS)
#define MREG_BCN_DTIM_OFST (MAC_REG_BASE + OFST_MREG_BCN_DTIM_OFST)
#define MREG_BCN_PERIOD    (MAC_REG_BASE + OFST_MREG_BCN_PERIOD)
#define MREG_DTIM_PERIOD   (MAC_REG_BASE + OFST_MREG_DTIM_PERIOD)
#define MREG_DTIM_COUNT    (MAC_REG_BASE + OFST_MREG_DTIM_COUNT)
#define MREG_PRE_TBTT      (MAC_REG_BASE + OFST_MREG_PRE_TBTT)
#define MREG_TBTT_TIMER    (MAC_REG_BASE + OFST_MREG_TBTT_TIMER)
#define MREG_TMPTT_TIMER   (MAC_REG_BASE + OFST_MREG_TMPTT_TIMER)

#define MREG_ACTZONE      (MAC_REG_BASE + OFST_MREG_ACTZONE)
#define MREG_WAVEUP_TIME0 (MAC_REG_BASE + OFST_MREG_WAVEUP_TIME0)
#define MREG_WAVEUP_TIME1 (MAC_REG_BASE + OFST_MREG_WAVEUP_TIME1)
#define MREG_WAVEUP_TIME2 (MAC_REG_BASE + OFST_MREG_WAVEUP_TIME2)
#define MREG_REST_TBTT    (MAC_REG_BASE + OFST_MREG_REST_TBTT)
#define MREG_MSEQ16       (MAC_REG_RBASE + OFST_MREG_MSEQ16)
#define MREG_CCA_DELAY    (MAC_REG_BASE + OFST_MREG_CCA_DELAY)

#define MREG_RDY_TIMEOUT       (MAC_REG_BASE + OFST_MREG_RDY_TIMEOUT)
#define MREG_RX_TIMEOUT        (MAC_REG_BASE + OFST_MREG_RX_TIMEOUT)
#define MREG_TBTT_ACT_TIME     (MAC_REG_BASE + OFST_MREG_TBTT_ACT_TIME)
#define MREG_TBTT_WAKEUP_TIME  (MAC_REG_BASE + OFST_MREG_TBTT_WAKEUP_TIME)
#define MREG_TMPTT_ACT_TIME    (MAC_REG_BASE + OFST_MREG_TMPTT_ACT_TIME)
#define MREG_TMPTT_WAKEUP_TIME (MAC_REG_BASE + OFST_MREG_TMPTT_WAKEUP_TIME)

#define MREG_RF_WAKEUP_TIME (MAC_REG_BASE + OFST_MREG_RF_WAKEUP_TIME)

#define MREG_TXPE_HOLD       (MAC_REG_BASE + OFST_MREG_TXPE_HOLD)
#define MREG_TXDELAY         (MAC_REG_BASE + OFST_MREG_TXDELAY)
#define MREG_RXDELAY         (MAC_REG_BASE + OFST_MREG_RXDELAY)
#define MREG_TRXPRE_INTERVAL (MAC_REG_BASE + OFST_MREG_TRXPRE_INTERVAL)

#define MREG_RXBUF_STR (MAC_REG_RBASE + OFST_MREG_RXBUF_STR)
#define MREG_RXBUF_END (MAC_REG_RBASE + OFST_MREG_RXBUF_END)

#define MREG_RDMA_STR  (MAC_REG_RBASE + OFST_MREG_RDMA_STR)
#define MREG_RDMA_CNT  (MAC_REG_RBASE + OFST_MREG_RDMA_CNT)
#define MREG_RDMA_JUMP (MAC_REG_RBASE + OFST_MREG_RDMA_JUMP)
#define MREG_RDMA_JCNT (MAC_REG_RBASE + OFST_MREG_RDMA_JUMP_CNT)
#define MREG_RDMA_PORT (MAC_DMA_BASE + OFST_MREG_RDMA_PORT)

#define MREG_WDMA_STR  (MAC_REG_RBASE + OFST_MREG_WDMA_STR)
#define MREG_WDMA_CNT  (MAC_REG_RBASE + OFST_MREG_WDMA_CNT)
#define MREG_WDMA_JUMP (MAC_REG_RBASE + OFST_MREG_WDMA_JUMP)
#define MREG_WDMA_JCNT (MAC_REG_RBASE + OFST_MREG_WDMA_JUMP_CNT)
#define MREG_WDMA_PORT (MAC_DMA_BASE + OFST_MREG_WDMA_PORT)

#define MREG_RXBUF_CUR   (MAC_REG_BASE + OFST_MREG_RXBUF_CUR)
#define MREG_RXBUF_WCUR  (MAC_REG_BASE + OFST_MREG_RXBUF_WCUR)
#define MREG_RXSTATUS    (MAC_REG_BASE + OFST_MREG_RX_STATUS)
#define MREG_RXBUF_BNR   (MAC_REG_BASE + OFST_MREG_RXBUF_BNR)
#define MREG_RXBUFOVF_TH (MAC_REG_BASE + OFST_MREG_RXBUFOVF_TH)
#define MREG_DEFRAG_OFST (MAC_REG_BASE + OFST_MREG_DEFRAG_OFST)

#define MREG_CNTUP_ISR  (MAC_REG_BASE + OFST_MREG_CNTUP_ISR)
#define MREG_CNTUP_IMR  (MAC_REG_BASE + OFST_MREG_CNTUP_IMR)
#define MREG_CNTOVF_ISR (MAC_REG_BASE + OFST_MREG_CNTOVF_ISR)
#define MREG_CNTOVF_IMR (MAC_REG_BASE + OFST_MREG_CNTOVF_IMR)

#define MREG_RXCOUNTER (MAC_REG_BASE + OFST_MREG_RXCOUNTER)

#define MREG_RXPLCP_CRC_ERR (MAC_REG_BASE + OFST_MREG_RXPLCP_CRC_ERR)
#define MREG_RXPLCP_BDY_ERR (MAC_REG_BASE + OFST_MREG_RXPLCP_BDY_ERR)
#define MREG_RXBUF_ERR      (MAC_REG_BASE + OFST_MREG_RXBUF_ERR)
#define MREG_RXFCS_OK_ERR   (MAC_REG_BASE + OFST_MREG_RXFCS_OK_ERR)
#define MREG_RXFC_ERR       (MAC_REG_BASE + OFST_MREG_RXFC_ERR)
#define MREG_RXRTS          (MAC_REG_BASE + OFST_MREG_RXRTS)
#define MREG_RXICV_OK_ERR   (MAC_REG_BASE + OFST_MREG_RXICV_OK_ERR)
#define MREG_DUP_ERR        (MAC_REG_BASE + OFST_MREG_DUP_ERR)
#define MREG_ACK_ERR        (MAC_REG_BASE + OFST_MREG_ACK_ERR)
#define MREG_RXS_CNT        (MAC_REG_BASE + OFST_MREG_RXS_CNT)
#define MREG_RES_CRR_CNT    (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_01)
#define MREG_RES_CRR_CNT_01 (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_01)
#define MREG_RES_CRR_CNT_23 (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_23)
#define MREG_RES_CRR_CNT_45 (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_45)
#define MREG_RES_CRR_CNT_67 (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_67)
#define MREG_RES_CRR_CNT_89 (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_89)
#define MREG_RES_CRR_CNT_AB (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_AB)
#define MREG_RES_CRR_CNT_CD (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_CD)
#define MREG_RES_CRR_CNT_EF (MAC_REG_BASE + OFST_MREG_RES_CRR_CNT_EF)

#define MREG_KEYIN_ADRS  (MAC_REG_BASE + OFST_MREG_KEYIN_ADRS)
#define MREG_KEYOUT_ADRS (MAC_REG_BASE + OFST_MREG_KEYOUT_ADRS)
#define MREG_SLOT_CONFIG (MAC_REG_BASE + OFST_MREG_SLOT_CONFIG)
#define MREG_TXQ         (MAC_REG_BASE + OFST_MREG_TXQ0)
#define MREG_TXQ0        (MAC_REG_BASE + OFST_MREG_TXQ0)
#define MREG_TXQ1        (MAC_REG_BASE + OFST_MREG_TXQ1)
#define MREG_TXQ2        (MAC_REG_BASE + OFST_MREG_TXQ2)
#define MREG_TXQ_CLOSE   (MAC_REG_BASE + OFST_MREG_TXQ_CLOSE)
#define MREG_TXQ_OPEN    (MAC_REG_BASE + OFST_MREG_TXQ_OPEN)
#define MREG_TXQ_MAP     (MAC_REG_BASE + OFST_MREG_TXQ_MAP)
#define MREG_TXQ_RESET   (MAC_REG_BASE + OFST_MREG_TXQ_RESET)
#define MREG_TXQ_CURR    (MAC_REG_BASE + OFST_MREG_TXQ_CURR)

#define MREG_MP_ADRS   (MAC_REG_BASE + OFST_MREG_MP_ADRS)
#define MREG_MP_DUR    (MAC_REG_BASE + OFST_MREG_MP_DUR)
#define MREG_MP_TXOP   (MAC_REG_BASE + OFST_MREG_MP_TXOP)
#define MREG_MP_TMPTT  (MAC_REG_BASE + OFST_MREG_MP_TMPTT)
#define MREG_MP_RESULT (MAC_REG_BASE + OFST_MREG_MP_RESULT)

#define MREG_TXSTATUS (MAC_REG_BASE + OFST_MREG_TXSTATUS)

#define MREG_MDP_CONFIG  (MAC_REG_BASE + OFST_MREG_MDP_CONFIG)
#define MREG_WEP_CONFIG  (MAC_REG_BASE + OFST_MREG_WEP_CONFIG)
#define MREG_DMA_CTRL    (MAC_REG_BASE + OFST_MREG_DMA_CTRL)
#define MREG_WDP_CTRL    (MAC_REG_BASE + OFST_MREG_WDP_CTRL)
#define MREG_SHUTDOWN    (MAC_REG_RBASE + OFST_MREG_SHUTDOWN)
#define MREG_WAKEUP_CTRL (MAC_REG_BASE + OFST_MREG_WAKEUP_CTRL)

#define MREG_MDP_JUMP_TST   (MAC_REG_BASE + OFST_MREG_MDP_JUMP_TST)
#define MREG_TX_TEST_MODE   (MAC_REG_BASE + OFST_MREG_TX_TEST_MODE)
#define MREG_TXTST_CMD      (MAC_REG_BASE + OFST_MREG_TXTST_CMD)
#define MREG_TXTST_PARAM    (MAC_REG_BASE + OFST_MREG_TXTST_PARAM)
#define MREG_MP_TEST        (MAC_REG_BASE + OFST_MREG_MP_TEST)
#define MREG_EN_DIRECT_CTL  (MAC_REG_BASE + OFST_MREG_EN_DIRECT_CTL)
#define MREG_SIGNAL_STATE   (MAC_REG_BASE + OFST_MREG_SIGNAL_STATE)
#define MREG_SERIAL_DAT_SEL (MAC_REG_RBASE + OFST_MREG_SERIAL_DAT_SEL)
#define MREG_SP_DIRECT      (MAC_REG_RBASE + OFST_MREG_SP_DIRECT)

#define MREG_MAC_STATE     (MAC_REG_RBASE + OFST_MREG_MAC_STATE)
#define MREG_TXS_TX_STATUS (MAC_REG_RBASE + OFST_MREG_TXS_TX_STATUS)

#define MREG_ANTENNA (MAC_REG_RBASE + OFST_MREG_ANTENNA)

#define MREG_BBP_CMD  (MAC_REG_RBASE + OFST_MREG_BBP_CMD)
#define MREG_BBP_WDAT (MAC_REG_RBASE + OFST_MREG_BBP_WDAT)
#define MREG_BBP_RDAT (MAC_REG_RBASE + OFST_MREG_BBP_RDAT)
#define MREG_BBP_STS  (MAC_REG_RBASE + OFST_MREG_BBP_STS)
#define MREG_BBP_CFG  (MAC_REG_RBASE + OFST_MREG_BBP_CFG)

#if (NEW_SDV)
#define MREG_RF_CMD (MAC_REG_RBASE + OFST_MREG_RF_CMD)
#define MREG_RF_DAT (MAC_REG_RBASE + OFST_MREG_RF_DAT)
#define MREG_RF_STS (MAC_REG_RBASE + OFST_MREG_RF_STS)
#define MREG_RF_CFG (MAC_REG_RBASE + OFST_MREG_RF_CFG)
#else
#define MREG_RF_CMD  (MAC_REG_RBASE + OFST_MREG_RF_CMD)
#define MREG_RF_WDAT (MAC_REG_RBASE + OFST_MREG_RF_WDAT)
#define MREG_RF_RDAT (MAC_REG_RBASE + OFST_MREG_RF_RDAT)
#define MREG_RF_STS  (MAC_REG_RBASE + OFST_MREG_RF_STS)
#define MREG_RF_CFG  (MAC_REG_RBASE + OFST_MREG_RF_CFG)
#endif

#define MREG_SCF_DIRECT (MAC_REG_RBASE + OFST_MREG_SCF_DIRECT)

#define MREG_ROM_CMD  (MAC_REG_RBASE + OFST_MREG_ROM_CMD)
#define MREG_ROM_WDAT (MAC_REG_RBASE + OFST_MREG_ROM_WDAT)
#define MREG_ROM_RDAT (MAC_REG_RBASE + OFST_MREG_ROM_RDAT)
#define MREG_ROM_STS  (MAC_REG_RBASE + OFST_MREG_ROM_STS)
#define MREG_ROM_CFG  (MAC_REG_RBASE + OFST_MREG_ROM_CFG)

#define MREG_SLOT_MEASURE (MAC_REG_BASE + OFST_MREG_SLOT_MEASURE)
#define MREG_CURR_SEQCTRL (MAC_REG_BASE + OFST_MREG_CURR_SEQCTRL)
#define MREG_JUMP_TST     (MAC_REG_BASE + OFST_MREG_JUMP_TST)

#define MREG_TXCOUNT (MAC_REG_BASE + OFST_MREG_TXCOUNT)

#define MREG_DDO (MAC_REG_RBASE + OFST_MREG_DDO)

#define MREG_WDP_STR_BUF_ADRS  (MAC_REG_BASE + OFST_MREG_WDP_BUF_STR_ADRS)
#define MREG_WDP_CUR_BUF_ADRS  (MAC_REG_BASE + OFST_MREG_WDP_CUR_BUF_ADRS)
#define MREG_WDP_MSDU_END_ADRS (MAC_REG_BASE + OFST_MREG_WDP_MSDU_END_ADRS)

#define MREG_LAST_RX_ADRS0 (MAC_REG_BASE + OFST_MREG_LAST_RX_ADRS2)
#define MREG_LAST_RX_ADRS1 (MAC_REG_BASE + OFST_MREG_LAST_RX_ADRS2 + 2)
#define MREG_LAST_RX_ADRS2 (MAC_REG_BASE + OFST_MREG_LAST_RX_ADRS2 + 4)

#define MREG_DCF_LAST_ADRS0   (MAC_MEM_BASE + 0x1f70)
#define MREG_DCF_LAST_ADRS1   (MAC_MEM_BASE + 0x1f72)
#define MREG_DCF_LAST_ADRS2   (MAC_MEM_BASE + 0x1f74)
#define MREG_DCF_LAST_SEQCTRL (MAC_MEM_BASE + 0x1f76)
#define MREG_MP_LAST_ADRS0    (MAC_MEM_BASE + 0x1f78)
#define MREG_MP_LAST_ADRS1    (MAC_MEM_BASE + 0x1f7a)
#define MREG_MP_LAST_ADRS2    (MAC_MEM_BASE + 0x1f7c)
#define MREG_MP_LAST_SEQCTRL  (MAC_MEM_BASE + 0x1f7e)

#define OFST_MREG_VERSION  0x000
#define OFST_MREG_CMD      0x004
#define OFST_MREG_CONFIG   0x006
#define OFST_MREG_TXCONFIG 0x008
#define OFST_MREG_RXCONFIG 0x00A

#define OFST_MREG_ISR 0x010
#define OFST_MREG_IMR 0x012

#define OFST_MREG_MAC_ADRS    0x018
#define OFST_MREG_MAC_ADRS0   0x018
#define OFST_MREG_MAC_ADRS1   0x01A
#define OFST_MREG_MAC_ADRS2   0x01C
#define OFST_MREG_BSSID       0x020
#define OFST_MREG_BSSID0      0x020
#define OFST_MREG_BSSID1      0x022
#define OFST_MREG_BSSID2      0x024
#define OFST_MREG_KSID        0x028
#define OFST_MREG_AID         0x02A
#define OFST_MREG_RETRY_LIMIT 0x02C
#define OFST_MREG_BASIC_RATE  0x02E

#define OFST_MREG_MDP_CONFIG  0x030
#define OFST_MREG_WEP_CONFIG  0x032
#define OFST_MREG_MOD_CTRL    0x034
#define OFST_MREG_SHUTDOWN    0x036
#define OFST_MREG_WAKEUP_CTRL 0x038

#define OFST_MREG_SET_POWER       0x03C
#define OFST_MREG_SET_FORCE_POWER 0x040

#define OFST_MREG_MP_POWER_SEQ 0x048
#define OFST_MREG_MSEQ16       0x044

#define OFST_MREG_RXBUF_STR  0x050
#define OFST_MREG_RXBUF_END  0x052
#define OFST_MREG_RXBUF_CUR  0x054
#define OFST_MREG_RXBUF_WCUR 0x056
#define OFST_MREG_RXBUF_BNR  0x05A

#define OFST_MREG_RDMA_STR      0x058
#define OFST_MREG_RDMA_CNT      0x05C
#define OFST_MREG_RDMA_JUMP     0x062
#define OFST_MREG_RDMA_JUMP_CNT 0x064
#define OFST_MREG_RDMA_PORT     0x060

#define OFST_MREG_WDMA_STR      0x068
#define OFST_MREG_WDMA_CNT      0x06C
#define OFST_MREG_WDMA_JUMP     0x074
#define OFST_MREG_WDMA_JUMP_CNT 0x076
#define OFST_MREG_WDMA_PORT     0x070
#define OFST_MREG_DMA_CTRL      0x078

#define OFST_MREG_BCN_ADRS      0x080
#define OFST_MREG_BCN_DTIM_OFST 0x084
#define OFST_MREG_BCN_PERIOD    0x08C
#define OFST_MREG_DTIM_PERIOD   0x08E
#define OFST_MREG_DTIM_COUNT    0x088

#define OFST_MREG_KEYIN_ADRS  0x094
#define OFST_MREG_KEYOUT_ADRS 0x098
#define OFST_MREG_SLOT_CONFIG 0x09C
#define OFST_MREG_TXQ0        0x0A0
#define OFST_MREG_TXQ1        0x0A4
#define OFST_MREG_TXQ2        0x0A8
#define OFST_MREG_TXQ_CLOSE   0x0AC
#define OFST_MREG_TXQ_OPEN    0x0AE
#define OFST_MREG_TXQ_MAP     0x0B0
#define OFST_MREG_TXQ_RESET   0x0B4
#define OFST_MREG_TXQ_CURR    0x0B6

#define OFST_MREG_TXSTATUS        0x0B8
#define OFST_MREG_TXERR_STATUS    0x0BA
#define OFST_MREG_TXPREAMBLE_TYPE 0x0BC

#define OFST_MREG_MP_ADRS   0x090
#define OFST_MREG_MP_DUR    0x0C0
#define OFST_MREG_MP_TXOP   0x0C4
#define OFST_MREG_MP_TMPTT  0x118
#define OFST_MREG_MP_RESULT 0x0C8

#define OFST_MREG_BUF_SELECT    0x0D0
#define OFST_MREG_RESPONSE_CTRL 0x0D4
#define OFST_MREG_BUFOVF_TH     0x0D8
#define OFST_MREG_DEFRAG_OFST   0x0DA

#define OFST_MREG_DS_MASK 0x0E0

#define OFST_MREG_TSF_ENABLE   0x0E8
#define OFST_MREG_TBTT_ENABLE  0x0EA
#define OFST_MREG_NAV_ENABLE   0x0EC
#define OFST_MREG_TMPTT_ENABLE 0x0EE

#define OFST_MREG_NEXT_TBTT_TSF  0x0F0
#define OFST_MREG_NEXT_TBTT_TSF0 0x0F0
#define OFST_MREG_NEXT_TBTT_TSF1 0x0F2
#define OFST_MREG_NEXT_TBTT_TSF2 0x0F4
#define OFST_MREG_NEXT_TBTT_TSF3 0x0F6
#define OFST_MREG_TSF            0x0F8
#define OFST_MREG_TSF0           0x0F8
#define OFST_MREG_TSF1           0x0FA
#define OFST_MREG_TSF2           0x0FC
#define OFST_MREG_TSF3           0x0FE
#define OFST_MREG_RXED_TSF       0x100
#define OFST_MREG_RXED_TSF0      0x102
#define OFST_MREG_RXED_TSF1      0x104
#define OFST_MREG_RXED_TSF2      0x106
#define OFST_MREG_RXED_TSF3      0x108

#define OFST_MREG_NAV 0x10C

#define OFST_MREG_PRE_TBTT       0x110
#define OFST_MREG_MP_WAKEUP_TIME 0x114
#define OFST_MREG_TMPTT_TIMER    0x118
#define OFST_MREG_TBTT_TIMER     0x11C

#define OFST_MREG_RDY_TIMEOUT       0x120
#define OFST_MREG_RX_TIMEOUT        0x122
#define OFST_MREG_TMPTT_ACT_TIME    0x124
#define OFST_MREG_TMPTT_WAKEUP_TIME 0x126
#define OFST_MREG_TBTT_ACT_TIME     0x128
#define OFST_MREG_TBTT_WAKEUP_TIME  0x12A

#define OFST_MREG_RESPONSE_TIMEOUT 0x130
#define OFST_MREG_ACK_CCA_TIMEOUT  0x132
#define OFST_MREG_ACTZONE          0x134

#define OFST_MREG_TS_TXOFST       0x140
#define OFST_MREG_TS_RXOFST       0x142
#define OFST_MREG_CCA_DELAY       0x144
#define OFST_MREG_TXPE_HOLD       0x146
#define OFST_MREG_TXDELAY         0x148
#define OFST_MREG_RXDELAY         0x14A
#define OFST_MREG_TRXPRE_INTERVAL 0x14C

#define OFST_MREG_RF_WAKEUP_TIME 0x150
#define OFST_MREG_MPACK_DELAY    0x154

#define OFST_MREG_BBP_CMD  0x158
#define OFST_MREG_BBP_WDAT 0x15A
#define OFST_MREG_BBP_RDAT 0x15C
#define OFST_MREG_BBP_STS  0x15E
#define OFST_MREG_BBP_CFG  0x160

#define OFST_MREG_RF_CMD 0x17C
#define OFST_MREG_RF_DAT 0x17E
#define OFST_MREG_RF_STS 0x180
#define OFST_MREG_RF_CFG 0x184

#define OFST_MREG_SCF_DIRECT 0x168

#define OFST_MREG_ROM_CMD  0x170
#define OFST_MREG_ROM_WDAT 0x172
#define OFST_MREG_ROM_RDAT 0x174
#define OFST_MREG_ROM_STS  0x176
#define OFST_MREG_ROM_CFG  0x178

#define OFST_MREG_MP_BURST_TEST  0x190
#define OFST_MREG_TX_TEST_MODE   0x194
#define OFST_MREG_RX_TEST_MODE   0x198
#define OFST_MREG_SIGNAL_STATE   0x19C
#define OFST_MREG_EN_DIRECT_CTL  0x1A0
#define OFST_MREG_SERIAL_DAT_SEL 0x1A2
#define OFST_MREG_SP_DIRECT      0x1A4

#define OFST_MREG_CNTUP_ISR  0x1A8
#define OFST_MREG_CNTUP_IMR  0x1AA
#define OFST_MREG_CNTOVF_ISR 0x1AC
#define OFST_MREG_CNTOVF_IMR 0x1AE

#define OFST_MREG_RXCOUNTER 0x1B0

#define OFST_MREG_RXPLCP_CRC_ERR 0x1B0
#define OFST_MREG_RXPLCP_BDY_ERR 0x1B2
#define OFST_MREG_RXBUF_ERR      0x1B4
#define OFST_MREG_RXFCS_OK_ERR   0x1B6
#define OFST_MREG_RXFC_ERR       0x1B8
#define OFST_MREG_RXRTS          0x1BA
#define OFST_MREG_RXICV_OK_ERR   0x1BC
#define OFST_MREG_DUP_ERR        0x1BE
#define OFST_MREG_ACK_ERR        0x1C0

#define OFST_MREG_RXS_CNT 0x1C4

#define OFST_MREG_RES_CRR_CNT_01 0x1D0
#define OFST_MREG_RES_CRR_CNT_23 0x1D2
#define OFST_MREG_RES_CRR_CNT_45 0x1D4
#define OFST_MREG_RES_CRR_CNT_67 0x1D6
#define OFST_MREG_RES_CRR_CNT_89 0x1D8
#define OFST_MREG_RES_CRR_CNT_AB 0x1DA
#define OFST_MREG_RES_CRR_CNT_CD 0x1DC
#define OFST_MREG_RES_CRR_CNT_EF 0x1DE

#define OFST_MREG_SLOT_MEASURE  0x208
#define OFST_MREG_CURR_SEQCTRL  0x210
#define OFST_MREG_MAC_STATE     0x214
#define OFST_MREG_ISR_TEST_SET  0x21C
#define OFST_MREG_MAIN_MUTE     0x220
#define OFST_MREG_RX_RESP_DBG   0x224
#define OFST_MREG_MAIN_ST       0x228
#define OFST_MREG_BYTE_WORD_DIR 0x238
#define OFST_MREG_TXS_TX_STATUS 0x23C
#define OFST_MREG_JUMP_TST      0x244
#define OFST_MREG_WDP_CONFIG    0x248
#define OFST_MREG_LAST_RX_ADRS2 0x24C
#define OFST_MREG_DDO           0x254

#define OFST_MREG_LAST_RSSI         0x258
#define OFST_MREG_WDP_STATUS        0x25C
#define OFST_MREG_WDP_BYTE_COUNT    0x260
#define OFST_MREG_WDP_BUF_STR_ADRS  0x264
#define OFST_MREG_WDP_CUR_BUF_ADRS  0x268
#define OFST_MREG_WDP_MSDU_STR_ADRS 0x26C
#define OFST_MREG_WDP_MSDU_END_ADRS 0x270
#define OFST_MREG_WDP_DEFRAG_CNT    0x274
#define OFST_MREG_LAST_SEQCTRL      0x278
#define OFST_MREG_RX_STATUS         0x27C
#define OFST_MREG_WLESS_CTRL1       0x284
#define OFST_MREG_WLESS_CTRL2       0x288
#define OFST_MREG_ANTENNA           0x290
#define OFST_MREG_TRF_CTRL          0x298
#define OFST_MREG_TRF_TXRATE        0x2A4
#define OFST_MREG_TRF_LEN_NORMAL    0x2A8
#define OFST_MREG_TRF_LEN_SEL       0x2AC
#define OFST_MREG_TRF_LEN_INPLCP    0x2B0
#define OFST_MREG_TXCOUNT           0x2B8

#define OFST_MREG_LAST_RATESVC 0x2C4
#define OFST_MREG_LAST_RAWLEN  0x2C8
#define OFST_MREG_LAST_FC      0x2CC

#define MACCMD_RST_BBP    (0x0001 << 15)
#define MACCMD_RST_MAC    (0x0001 << 14)
#define MACCMD_PWR_ACTIVE (0x0000 << 8)
#define MACCMD_PWR_SLEEP1 (0x0001 << 8)
#define MACCMD_PWR_SLEEP2 (0x0002 << 8)
#define MACCMD_PWR_SLEEP3 (0x0003 << 8)
#define MACCMD_RST_RX     (0x0001 << 4)
#define MACCMD_RST_TX     (0x0001 << 3)
#define MACCMD_START      (0x0001 << 0)

#define MACCFG_PWR_PS       (0x0001 << 6)
#define MACCFG_PWR_ACT      (0x0000 << 6)
#define MACCFG_WEP_NO       (0x0001 << 3)
#define MACCFG_WEP_40       (0x0001 << 3)
#define MACCFG_WEP_104      (0x0002 << 3)
#define MACCFG_WEP_128      (0x0003 << 3)
#define MACCFG_WEP_232      (0x0004 << 3)
#define MACCFG_WORK_TEST    (0x0000 << 0)
#define MACCFG_WORK_PARENT  (0x0001 << 0)
#define MACCFG_WORK_CHILD   (0x0002 << 0)
#define MACCFG_WORK_HOTSPOT (0x0003 << 0)

#define MACCFG_WEP_MASK  (0x0007 << 3)
#define MACCFG_WORK_MASK (0x0007 << 0)

#define TXCFG_INT_BCN    (0x0001 << 15)
#define TXCFG_INT_MP     (0x0001 << 14)
#define TXCFG_INT_MP_ACK (0x0001 << 13)
#define TXCFG_INT_RES_MP (0x0001 << 12)

#define RXCFG_NCHK_BCN_DUP  (0x0001 << 7)
#define RXCFG_RX_BCN        (0x0001 << 6)
#define RXCFG_DIFF_BSSID_UC (0x0001 << 5)
#define RXCFG_DIFF_BSSID_BC (0x0001 << 4)

#define MISR_PRE_TBTT   (0x0001 << 15)
#define MISR_TBTT       (0x0001 << 14)
#define MISR_ACTEND     (0x0001 << 13)
#define MISR_MPEND      (0x0001 << 12)
#define MISR_RF_WAKEUP  (0x0001 << 11)
#define MISR_RDMA_END   (0x0001 << 9)
#define MISR_WDMA_END   (0x0001 << 8)
#define MISR_START_TX   (0x0001 << 7)
#define MISR_START_RX   (0x0001 << 6)
#define MISR_ACKCNT_OVF (0x0001 << 5)
#define MISR_CNT_OVF    (0x0003 << 4)
#define MISR_TXERR      (0x0001 << 3)
#define MISR_RXCNTUP    (0x0001 << 2)
#define MISR_TXEND      (0x0001 << 1)
#define MISR_RXEND      (0x0001 << 0)

#define MIMR_PRE_TBTT  (0x0001 << 15)
#define MIMR_TBTT      (0x0001 << 14)
#define MIMR_ACTEND    (0x0001 << 13)
#define MIMR_MPEND     (0x0001 << 12)
#define MIMR_RF_WAKEUP (0x0001 << 11)
#define MIMR_TXEND_TST (0x0001 << 9)
#define MIMR_RXEND_TST (0x0001 << 8)
#define MIMR_RDMA_END  (0x0001 << 7)
#define MIMR_WDMA_END  (0x0001 << 6)
#define MIMR_CNT_OVF   (0x0001 << 4)
#define MIMR_TXERR     (0x0001 << 3)
#define MIMR_RXCNTUP   (0x0001 << 2)
#define MIMR_TXEND     (0x0001 << 1)
#define MIMR_RXEND     (0x0001 << 0)

#define PRE_MP_LONG      (0x0000 << 0)
#define PRE_MP_SHORT     (0x0001 << 0)
#define PRE_DCF_LONG     (0x0000 << 1)
#define PRE_DCF_SHORT    (0x0001 << 1)
#define PRE_BEACON_LONG  (0x0000 << 2)
#define PRE_BEACON_SHORT (0x0001 << 2)

#define BM_PRE_MP     (0x0001 << 0)
#define BM_PRE_DCF    (0x0001 << 1)
#define BM_PRE_BEACON (0x0001 << 2)

#define BRS_2MBPS (0x0001 << 1)
#define BRS_1MBPS (0x0001 << 0)

#define BF_OTHER_BSSID_PSPOLL (0x0001 << 11)
#define BF_OTHER_BSSID_MAN    (0x0001 << 10)
#define BF_BC_BSSID_MAN       (0x0001 << 9)
#define BF_MP_NULLKEY         (0x0001 << 8)
#define BF_MP_ACK             (0x0001 << 7)
#define BF_CF_POLLACK_NULL    (0x0001 << 6)
#define BF_CF_POLL_NULL       (0x0001 << 5)
#define BF_CF_ACK_NULL        (0x0001 << 4)
#define BF_CF_POLLACK         (0x0001 << 3)
#define BF_CF_POLL            (0x0001 << 2)
#define BF_CF_ACK             (0x0001 << 1)
#define BF_OTHER_BSSID_BEACON (0x0001 << 0)

#define BF_TOFROMDS_11 (0x0001 << 3)
#define BF_TOFROMDS_01 (0x0001 << 2)
#define BF_TOFROMDS_10 (0x0001 << 1)
#define BF_TOFROMDS_00 (0x0001 << 0)

#define TODS_FROMDS_PARENT  (BF_TOFROMDS_11 | BF_TOFROMDS_01 | BF_TOFROMDS_00)
#define TODS_FROMDS_CHILD   (BF_TOFROMDS_11 | BF_TOFROMDS_10 | BF_TOFROMDS_00)
#define TODS_FROMDS_HOTSPOT (BF_TOFROMDS_11 | BF_TOFROMDS_10 | BF_TOFROMDS_00)
#define TODS_FROMDS_TEST    (BF_TOFROMDS_11)

#define SHDWN_ENABLE  1
#define SHDWN_DISABLE 0

#define PWR_STS_ACTIVE (0x0001 << 1)
#define PWR_STS_SLEEP  (0x0001 << 0)

#define FPWR_STS_ENABLE  (0x0001 << 15)
#define FPWR_STS_DISABLE (0x0000 << 15)
#define FPWR_STS_ACTIVE  ((0x0000 << 0) | FPWR_STS_ENABLE)
#define FPWR_STS_SLEEP   ((0x0001 << 0) | FPWR_STS_ENABLE)

#define MPPWR_WAKEUP   (0x0001 << 1)
#define MPPWR_ACTIVATE (0x0001 << 0)

#define TSFEN_ON  (0x0001 << 0)
#define TSFEN_OFF (0x0000 << 0)

#define TBTTEN_ON  (0x0001 << 0)
#define TBTTEN_OFF (0x0000 << 0)

#define TBTTFEN_ON  (0x0001 << 1)
#define TBTTFEN_OFF (0x0000 << 1)

#define NAV_ON                 (0x0001 << 0)
#define NAV_OFF                (0x0000 << 0)
#define NAV_CFP_BCN_ON         (0x0001 << 1)
#define NAV_CFP_BCN_OFF        (0x0001 << 1)
#define NAV_IGNORE             (0x0001 << 2)
#define NAV_CNT_HOLD           (0x0001 << 4)
#define NAV_IGNORE_KEYRESPONSE (0x0001 << 5)

#define WEP_CFG_ON  (0x8000)
#define WEP_CFG_OFF (0x0000)

#define TS_TXOFST_1M   (0x00e6 * 0x0001)
#define TS_TXOFST_2M_L (0x0085 * 0x0001)
#define TS_TXOFST_2M_S (0x0026 * 0x0001)

#define TS_TXOFST_BCN_1M   (TS_TXOFST_1M * 0x0001)
#define TS_TXOFST_BCN_2M_L (TS_TXOFST_2M_L * 0x0001)
#define TS_TXOFST_BCN_2M_S (TS_TXOFST_2M_S * 0x0001)
#define TS_TXOFST_PRB_1M   (TS_TXOFST_1M * 0x0100)
#define TS_TXOFST_PRB_2M_L (TS_TXOFST_2M_L * 0x0100)
#define TS_TXOFST_PRB_2M_S (TS_TXOFST_2M_S * 0x0100)

#define TS_RXOFST_2M (0x0001 << 8)
#define TS_RXOFST_1M (0x0001 << 0)

#define TMSTS_TX (0x0001 << 1)
#define TMSTS_RX (0x0001 << 0)

#define BCNADRS_EN (0x0001 << 15)
#define BCNADRS    (0x0001 << 0)

#define BCNPARAM_DTIM (0x0001 << 0)

#define RXSTS_MATCHBSSID (0x0001 << 15)
#define RXSTS_TX_KEY     (0x0001 << 14)
#define RXSTS_POLLED_MP  (0x0001 << 13)
#define RXSTS_KEY_IN     (0x0001 << 12)
#define RXSTS_KEY_OUT    (0x0001 << 11)
#define RXSTS_ICV_ERR    (0x0001 << 10)
#define RXSTS_INCOMPLETE (0x0001 << 9)
#define RXSTS_MOREFRAG   (0x0001 << 8)
#define RXSTS_FRAGCNT    (0x0001 << 4)
#define RXSTS_BEACON     (0x0001 << 0)
#define RXSTS_MAN        (0x0000 << 0)
#define RXSTS_PSPOLL     (0x0005 << 0)
#define RXSTS_CFEND      (0x0006 << 0)
#define RXSTS_CTRL       (0x0008 << 0)
#define RXSTS_MP         (0x000C << 0)
#define RXSTS_MPACK      (0x000D << 0)
#define RXSTS_KEY        (0x000E << 0)
#define RXSTS_NULLKEY    (0x000F << 0)
#define RXSTS_DATA       (0x0008 << 0)

#define RXSTS_FRAGCNT_MASK    (0x000F * RXSTS_FRAGCNT)
#define RXSTS_FRAME_TYPE_MASK (0x000F)

#define RXCNTSTS_MPDUP        (0x0001 << 12)
#define RXCNTSTS_EXMPDUP      (0x0001 << 11)
#define RXCNTSTS_ICV_OK       (0x0001 << 10)
#define RXCNTSTS_ICV_ERR      (0x0001 << 9)
#define RXCNTSTS_RTS          (0x0001 << 8)
#define RXCNTSTS_FC_ERR       (0x0001 << 7)
#define RXCNTSTS_FCS_OK       (0x0001 << 6)
#define RXCNTSTS_FCS_ERR      (0x0001 << 5)
#define RXCNTSTS_BUF_PATH_ERR (0x0001 << 4)
#define RXCNTSTS_BUF_OVF_ERR  (0x0001 << 3)
#define RXCNTSTS_LENGTH_ERR   (0x0001 << 2)
#define RXCNTSTS_SIGNAL_ERR   (0x0001 << 1)
#define RXCNTSTS_PLCP_ERR     (0x0001 << 0)

#define TXQ_ENABLE (0x0001 << 15)
#define TXQ_RESUME (0x0001 << 14)
#define TXQ_CTRL   (0x0001 << 13)
#define TXQ_PRBRES (0x0001 << 12)

#define TXQ_CLOSE_TXQ2 (0x0001 << 3)
#define TXQ_CLOSE_TXQ1 (0x0001 << 2)
#define TXQ_CLOSE_MP   (0x0001 << 1)
#define TXQ_CLOSE_TXQ0 (0x0001 << 0)

#define TXQ_OPEN_TXQ2 (0x0001 << 3)
#define TXQ_OPEN_TXQ1 (0x0001 << 2)
#define TXQ_OPEN_MP   (0x0001 << 1)
#define TXQ_OPEN_TXQ0 (0x0001 << 0)

#define TXQ_NBLOCK_TXQ2 (0x0001 << 3)
#define TXQ_NBLOCK_TXQ1 (0x0001 << 2)
#define TXQ_NBLOCK_MP   (0x0001 << 1)
#define TXQ_NBLOCK_TXQ0 (0x0001 << 0)

#define TXQ_RST_KEYIN  (0x0001 << 7)
#define TXQ_RST_KEYOUT (0x0001 << 6)
#define TXQ_RST_TXQ2   (0x0001 << 3)
#define TXQ_RST_TXQ1   (0x0001 << 2)
#define TXQ_RST_MP     (0x0001 << 1)
#define TXQ_RST_TXQ0   (0x0001 << 0)

#define TXQ_CURR_BEACON (0x0001 << 4)
#define TXQ_CURR_TXQ2   (0x0001 << 3)
#define TXQ_CURR_TXQ1   (0x0001 << 2)
#define TXQ_CURR_MP     (0x0001 << 1)
#define TXQ_CURR_TXQ0   (0x0001 << 0)

#define TXSTS_NORMAL    (0x0000 << 8)
#define TXSTS_BEACON    (0x0003 << 8)
#define TXSTS_KEY       (0x0004 << 8)
#define TXSTS_MP        (0x0008 << 8)
#define TXSTS_NULL      (0x0009 << 8)
#define TXSTS_MPACK     (0x000B << 8)
#define TXSTS_RETRY_ERR (0x0001 << 1)
#define TXSTS_FINISH    (0x0001 << 0)

#define TXSTS_FRAME_TYPE_MASK (0x000F << 8)

#define TXTEST_NOSEQCTRL (0x0001 << 2)
#define TXTEST_NOFCS     (0x0001 << 1)
#define TXTEST_TX        (0x0001 << 0)

#define SIGNAL_STATE_RXPE     (0x0001 << 7)
#define SIGNAL_STATE_TXPE     (0x0001 << 6)
#define SIGNAL_STATE_PLL_LOCK (0x0001 << 2)
#define SIGNAL_STATE_TRRDY    (0x0001 << 1)
#define SIGNAL_STATE_CCA      (0x0001 << 0)

#define ENG_RXPE_SET_HIGH ((0x0001 << 7) | ENG_RXPE_ENABLE)
#define ENG_RXPE_SET_LOW  ((0x0001 << 6) | ENG_RXPE_ENABLE)
#define ENG_RXPE_ENABLE   (0x0001 << 5)
#define ENG_RXPE_DISABLE  (0x0000 << 5)
#define ENG_TXPE_SET_HIGH ((0x0001 << 3) | ENG_TXPE_ENABLE)
#define ENG_TXPE_SET_LOW  ((0x0001 << 2) | ENG_TXPE_ENABLE)
#define ENG_TXPE_ENABLE   (0x0001 << 1)
#define ENG_TXPE_DISABLE  (0x0000 << 1)

#define WAKEUP_CTRL_SLP_MPACK    (0x0001 << 3)
#define WAKEUP_CTRL_SLP_MPKEY    (0x0001 << 2)
#define WAKEUP_CTRL_WAKEUP_TMPTT (0x0001 << 1)
#define WAKEUP_CTRL_WAKEUP_TBTT  (0x0001 << 0)

#define MAC_STATE_STANDBY 0
#define MAC_STATE_IDLE    1
#define MAC_STATE_PRETX   2
#define MAC_STATE_TX      3
#define MAC_STATE_POSTTX  4
#define MAC_STATE_WAIT    5
#define MAC_STATE_RX      6
#define MAC_STATE_PRERSP  7
#define MAC_STATE_RESP    8
#define MAC_STATE_SLEEP   9

#define SRLDEV_CMD              (0x0001 << 12)
#define SRLBBP_CMD_WRITE        (0x0005 * SRLDEV_CMD)
#define SRLBBP_CMD_READ         (0x0006 * SRLDEV_CMD)
#define SRLROM_CMD_READ         (0x0006 * SRLDEV_CMD)
#define SRLROM_CMD_WRITE_EN     (0x0004 * SRLDEV_CMD + 0xC0 * SRLDEV_CMD_ADRS)
#define SRLROM_CMD_WRITE        (0x0005 * SRLDEV_CMD)
#define SRLROM_CMD_WRITE_ALL    (0x0004 * SRLDEV_CMD + 0x40 * SRLDEV_CMD_ADRS)
#define SRLROM_CMD_WRITE_DIS    (0x0004 * SRLDEV_CMD + 0x00 * SRLDEV_CMD_ADRS)
#define SRLROM_CMD_ERASE        (0x0007 * SRLDEV_CMD)
#define SRLROM_CMD_ERASE_ALL    (0x0004 * SRLDEV_CMD + 0x80 * SRLDEV_CMD_ADRS)
#define SRLDEV_CMD_ADRS         (0x0001 << 0)
#define SRLDEV_STS_PROPE        (0x0001 << 5)
#define SRLDEV_STS_RETRY        (0x0001 << 3)
#define SRLDEV_STS_ACSING       (0x0001 << 2)
#define SRLDEV_STS_REQING       (0x0001 << 1)
#define SRLDEV_STS_BUSY         (0x0001 << 0)
#define SRLDEV_CFG_ERASE_PERIOD (0x0001 << 8)
#define SRLDEV_CFG_ADRSBITCNT   (0x0001 << 4)
#define SRLDEV_CFG_NOCMD        (0x0001 << 2)
#define SRLDEV_CFG_DATA12BIT    (0x0001 << 1)
#define SRLDEV_CFG_DATA8BIT     (0x0001 << 0)
#define SRLDEV_CFG_DATA16BIT    (0x0000 << 0)
#define SRLROM_SIZE_256W        256

#define SDV_RF_WRITE (0x0001 << 15)
#define SDV_RF_READ  (0x0000 << 15)
#define SDV_RF_DAT_H (0x0001 << 0)

#define SDV_RF_DAT_L (0x0001 << 0)

#define SDV_RF_BUSY (0x0001 << 0)

#define SDV_RF_CLK_8M   (0x0001 << 14)
#define SDV_RF_CLK_4M   (0x0000 << 14)
#define SDV_RF_ADD_CLK  (0x0001 << 8)
#define SDV_RF_BITCOUNT (0x0001 << 0)

#define BBPREG_CCA_MODE  0x13
#define BBPREG_ED_TH     0x35
#define BBPREG_AGC_LIMIT 0x2E

#define BP_CCA_MODE_0 0
#define BP_CCA_MODE_1 1
#define BP_CCA_MODE_2 2
#define BP_CCA_MODE_3 3

#endif // __MAC_H_
