#ifndef __PLATFORM_H_
#define __PLATFORM_H_

#define EMU_MACREG         0
#define INCLUDE_BBP_ES1    1
#define USE_FLASH          1
#define USE_EEPROM         1
#define USE_OS_PRINTF      0
#define BBP_RF_REGCHK      0
#define WL_WRAM_IN_MAINMEM 1
#define WL_HEAP_IN_MAINMEM 1
#define WL_USE_EXT_HEAPBUF 1
#define WL_NOTPS_VMAP1     1
#define WL_CHK_RATESET     0
#define INCLUDE_IPL        0

#ifndef SDK_TEG
#undef USE_FLASH
#undef USE_EEPROM
#undef USE_OS_PRINTF
#define USE_FLASH     1
#define USE_EEPROM    0
#define USE_OS_PRINTF 1
#endif

#ifdef SDK_NOCHK_ERR_WL
#undef USE_EEPROM
#define USE_EEPROM 0
#endif

#if EMU_MACREG
#undef WL_USE_EXT_HEAPBUF
#define WL_USE_EXT_HEAPBUF 0
#endif

#define MAX2822  1
#define MDRF2958 2
#define MM3156   3
#define TESTRF   4
#if (INCLUDE_BBP_ES1)
#define MTMBBP_ES1 5
#endif
#define MM3218 6

#define INTERSIL 1
#define MITSUMI  2

#define AT93C46 1
#define BR93L66 2

#define UseCpuCopy 1
#define UseDmaCopy 2
#define UseMemCopy 3
#define COPY_TYPE  UseDmaCopy

// #define WAIT_MA	0
// #define FAST_MA	1
// #define MA_TYPE	FAST_MA

#define MAINRAM   0
#define IOREG     1
#define CNTSTSSEL MAINRAM

#define MCLK 33.514

#define ASIC_TYPE   WS1
#define PLL_TYPE    MAX2822
#define BBP_TYPE    MITSUMI
#define EEPROM_TYPE BR93L66

// #undef	PLL_TYPE
// #define PLL_TYPE		MDRF2958
// #define PLL_TYPE		TESTRF
// #define	RF_ID			PLL_TYPE
#define RF_ID MDRF2958

#define RF_MAX2822_BITS     16
#define RF_MAX2822_INIT_NUM 5
#define RF_MAX2822_CHAN_NUM 1

#define RF_MDRF2958_BITS     24
#define RF_MDRF2958_INIT_NUM 12
#define RF_MDRF2958_CHAN_NUM 1

#define RF_MM3156_BITS     (20 + 0x80)
#define RF_MM3156_INIT_NUM 27
#define RF_MM3156_CHAN_NUM 3

#define RF_MM3156ES3_INIT_NUM 29
#define RF_MM3156ES3_CHAN_NUM 2

#define RF_MM3156CS1_INIT_NUM 29
#define RF_MM3156CS1_CHAN_NUM 2

#define RF_MM3156CS2_INIT_NUM 32
#define RF_MM3156CS2_CHAN_NUM 2

#define RF_MM3218_BITS     (20 + 0x80)
#define RF_MM3218_INIT_NUM 41
#define RF_MM3218_CHAN_NUM 2

#define RF_TESTRF_BITS     0
#define RF_TESTRF_INIT_NUM 0
#define RF_TESTRF_CHAN_NUM 0

#define WL_STALIST_ADRS      wlStaElement
#define WL_WORKADRS_BUF_ADRS (HW_PRV_WRAM_SYSRV + 0x34)
#define WL_VTSF_ADRS         (HW_PRV_WRAM_SYSRV + 0x30)

#if (WL_HEAP_IN_MAINMEM)
#define ARENA_SIZE 0x8000
#else
#define ARENA_SIZE 0x2100
#endif
#define HEAP_SIZE        (ARENA_SIZE - 0x48)
#define APP_HEAPBUF_SIZE 0x4000
#define WL_WORK_SIZE     0x0700
#define WL_STACK_SIZE    0x600
#define WL_CAMTABLE_NUM  16

#define IDLE_STACK_SIZE      0x10
#define TERMINATE_STACK_SIZE 0x100

#define SEND_MSG_NUM 10
#define RECV_MSG_NUM 10

#if (WL_HEAP_IN_MAINMEM)
#define HEAP_ARENA OS_ARENA_MAIN_SUBPRIV
#else
#define HEAP_ARENA OS_ARENA_WRAM_SUBPRIV
#endif

#define STACK_CHECK_ID 0xA1B2C3D4

#define EXT_RAM_START_ADRS (HW_MAIN_MEM_MAIN + 0x00280000)
#define EXT_RAM_END_ADRS   HW_MAIN_MEM_MAIN_END

#define SCMD_ARM9_TEMP_ADRS EXT_RAM_START_ADRS
#define SCMD_ARM9_TEMP_SIZE 0x800

#define RE_SCMD_ARM9_TEMP_ADRS (SCMD_ARM9_TEMP_ADRS + SCMD_ARM9_TEMP_SIZE)
#define RE_SCMD_ARM9_TEMP_SIZE 0x2000

#define ARM9_TO_ARM7_BUF_ADRS (RE_SCMD_ARM9_TEMP_ADRS + RE_SCMD_ARM9_TEMP_SIZE)
#define ARM9_TO_ARM7_BUF_SIZE 0x1000

#define REQ_LENGTH       (ARM9_TO_ARM7_BUF_ADRS + 0x00000100)
#define REQ_DATA_POINTER (ARM9_TO_ARM7_BUF_ADRS + 0x00000110)

#define ARM7_TO_ARM9_BUF_ADRS (ARM9_TO_ARM7_BUF_ADRS + ARM9_TO_ARM7_BUF_SIZE)
#define ARM7_TO_ARM9_BUF_SIZE 0x2000

#define IND_LENGTH       (ARM7_TO_ARM9_BUF_ADRS + 0x00000100)
#define IND_DATA_POINTER (ARM7_TO_ARM9_BUF_ADRS + 0x00000110)

#define ARM97_CNTL_STS_REG_ADRS (ARM7_TO_ARM9_BUF_ADRS + ARM7_TO_ARM9_BUF_SIZE)
#define ARM97_CNTL_STS_REG_SIZE 0x20

#define LCD_SHARE_MEM_ADRS (ARM97_CNTL_STS_REG_ADRS + ARM97_CNTL_STS_REG_SIZE)
#define LCD_SHARE_MEM_SIZE 0x4000

#define SCMD_SELECT_DEV_ADRS (LCD_SHARE_MEM_ADRS + LCD_SHARE_MEM_SIZE)
#define SCMD_SELECT_DEV_SIZE 0x4

#define TP_BUF_ADRS (SCMD_SELECT_DEV_ADRS + SCMD_SELECT_DEV_SIZE)
#define TP_BUF_SIZE (0x10 + 2 + 2 + 4 * 128)

#define TRACE_RAM_START_ADRS (SCMD_SELECT_DEV_ADRS + SCMD_SELECT_DEV_SIZE)
#define TRACE_RAM_SIZE       0x5000
#define TRACE_RAM_END_ADRS   (TRACE_RAM_START_ADRS + TRACE_RAM_SIZE)

#if (EMU_MACREG)
#undef MAC_REG_BASE
#define MAC_REG_BASE (0x020F0000)
#endif
#define MAC_REG_RBASE HW_WIRELESS_INTF1
#define MAC_DMA_BASE  HW_WIRELESS_INTF1
#define MAC_MEM_BASE  (HW_WIRELESS_INTF0 + 0x4000)

#define MAC_REG_SIZE 0x00000300
#define MAC_MEM_SIZE 0x00002000
#define BBP_REG_SIZE 105

#if (EEPROM_TYPE == AT93C46)
#define EEPROM_SIZE 0x040
#elif (EEPROM_TYPE == BR93L66)
#define EEPROM_SIZE 0x200
#endif

#define EEPROM_BBP_REG_SIZE   BBP_REG_SIZE
#define EEPROM_BBP_TXPWR_SIZE 2 * 14
#define EEPROM_RFINIT_SIZE    4 * 12
#define EEPROM_BASE           0
#define IRIS_EEPROM_BASE      0x100

#define NTD_EEPROM_SIZE 512

#endif // __PLATFORM_H_
