libspi_srcs = files(
    'tp.c',
    'mic.c',
    'pm.c'
)

libspi_arm7_srcs = files(
    'ARM7/spi.c'
)

libtp_arm7_srcs = files(
    'ARM7/tp/tp.c',
    'ARM7/tp/tp_sampling.c'
)

libpm_arm7_srcs = files(
    'ARM7/pm/pm.c',
    'ARM7/pm/pm_send.c',
    'ARM7/pm/pm_pmic.c',
    'ARM7/pm/pm_utility.c',
    'ARM7/pm/pm_sleep.c',
    'ARM7/pm/pm_selfBlink.c'
)

libmic_arm7_srcs = files(
    'ARM7/mic/mic.c',
    'ARM7/mic/mic_sampling.c',
    'ARM7/mic/mic_irq.c'
)

libnvram_arm7_srcs = files(
    'ARM7/nvram/nvram.c',
    'ARM7/nvram/nvram_instruction.c'
)
