libsnd_srcs = files(
    'snd_interface.c',
    'snd_main.c',
    'snd_command.c',
    'snd_alarm.c',
    'snd_work.c',
    'snd_util.c',
    'snd_bank.c',
    'snd_data.c'
)

libsnd_arm7_srcs = files(
    'ARM7/snd_global.c',
    'ARM7/snd_channel.c',
    'snd_util.c',
    'snd_main.c',
    'ARM7/snd_capture.c',
    'ARM7/snd_exchannel.c',
    'ARM7/snd_seq.c',
    'ARM7/snd_midiplayer.c',
    'snd_bank.c',
    'snd_work.c',
    'snd_alarm.c',
    'snd_command.c',
    'snd_data.c'
)
